### ISSUE TITLE
When testing the bot

### ISSUE THREAD

**Issue by ProximityMicrowave** [TreborNamor/Agressive-Bestbuy-Bot#1]
Button Found!: Add to Cart
Traceback (most recent call last):
  File "C:\Users\holyn\PycharmProjects\RTX3080 Bot\bestbuy.py", line 167, in <module>
    findingCards(driver)
  File "C:\Users\holyn\PycharmProjects\RTX3080 Bot\bestbuy.py", line 91, in findingCards
    driver.find_element_by_xpath("//*[@class='btn btn-lg btn-block btn-primary']").click()
  File "C:\Users\holyn\PycharmProjects\RTX3080 Bot\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\holyn\PycharmProjects\RTX3080 Bot\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\holyn\PycharmProjects\RTX3080 Bot\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\holyn\PycharmProjects\RTX3080 Bot\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: Element <button class="btn btn-lg btn-block btn-primary" type="button"> is not clickable at point (1151,464) because another element <div class="page-spinner page-spinner--out"> obscures it

**Comment by ProximityMicrowave** [comment]
Okay, I don't know what I did, but when I just deleted the project and started over it seems to have started working properly. Sorry to bother you.
