### ISSUE TITLE
Aggressive Newegg Bot - Starts Running But Stops When It Detects Button and Later Cannot Find It

### ISSUE THREAD

**Issue by deslumoprime** [TreborNamor/Agressive-Bestbuy-Bot#13]
When I run the Newegg Aggressive bot, it seems to detect some ATC button even though there isn't one. Here are the errors:

/Users/raymondzhang/PycharmProjects/neweggbot/venv/bin/python /Users/raymondzhang/PycharmProjects/neweggbot/main.py
[WDM] - Driver [/Users/raymondzhang/.wdm/drivers/geckodriver/macos/v0.29.0/geckodriver] found in cache

Button Found!: Add to cart 
Traceback (most recent call last):
  File "/Users/raymondzhang/PycharmProjects/neweggbot/main.py", line 184, in <module>
    findingCards(driver)

  File "/Users/raymondzhang/PycharmProjects/neweggbot/main.py", line 85, in findingCards
    driver.find_element_by_xpath("//*[@class='btn btn-primary btn-mini']").click()

  File "/Users/raymondzhang/PycharmProjects/neweggbot/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)

  File "/Users/raymondzhang/PycharmProjects/neweggbot/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)

  File "/Users/raymondzhang/PycharmProjects/neweggbot/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)

  File "/Users/raymondzhang/PycharmProjects/neweggbot/venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)

selenium.common.exceptions.ElementNotInteractableException: Message: Element <button class="btn btn-primary btn-mini"> could not be scrolled into view

Process finished with exit code 1

Is there anything I could do to fix this?

**Comment by TreborNamor** [comment]
The error is ElementNotInteractableException: Message: Element could not be scrolled into view.

It looks like it finds the button but it is not able to click it. I would try adding a sleep timer to your script for about 1 or 2 seconds. That should give the page enough time to load then script can click it properly.
![image](https://user-images.githubusercontent.com/59729477/105927512-c28e2600-6009-11eb-9794-c57f2e85561a.png)

**Comment by TreborNamor** [comment]
This happens when the computer tries to click the ATC button faster than webpage can load all elements.

**Comment by deslumoprime** [comment]
That fixed it, thank you! It's working now!
