### ISSUE TITLE
script wont run properly , please help

### ISSUE THREAD

**Issue by PumpkinAlpha** [TreborNamor/Agressive-Bestbuy-Bot#16]
Hi, I'm new to python so sorry in advance. whenever I run the code I get 5 error codes. I updated to the latest python and tried debugging it myself to no avail. the codes are: 
/Users/bahmandehkordi/PycharmProjects/pythonProject2/bestbuybot.py
Traceback (most recent call last):
  File "/Users/bahmandehkordi/PycharmProjects/pythonProject2/bestbuybot.py", line 166, in <module>
    driver = createDriver()
  File "/Users/bahmandehkordi/PycharmProjects/pythonProject2/bestbuybot.py", line 43, in createDriver
    profile = webdriver.FirefoxProfile(
  File "/Users/bahmandehkordi/PycharmProjects/pythonProject2/venv/lib/python3.9/site-packages/selenium/webdriver/firefox/firefox_profile.py", line 79, in __init__
    shutil.copytree(self.profile_dir, newprof,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 555, in copytree
    with os.scandir(src) as itr:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Trebor\\AppData\\Roaming\\Mozilla\\Firefox\\Profiles\\kwftlp36.default-release'

Process finished with exit code 1 

I uploaded my code to this [link](https://github.com/PumpkinAlpha/AgBot-rtx3080) (https://github.com/PumpkinAlpha/AgBot-rtx3080). any help would be greatly appreciated. thank you in advance.

**Comment by TreborNamor** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\Trebor\AppData\Roaming\Mozilla\Firefox\Profiles\kwftlp36.default-release'

On line 43 you need to put your firefox profile directory path inside the quotes. You can find a demonstration inside the youtube video here. https://youtu.be/RHG1084ad1o
