### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by IIe4eHbkas** [TreborNamor/Agressive-Bestbuy-Bot#25]
The script worked well for several days, but today, when I returned to the computer, I saw this at the end of the log:
...
Page refreshed
Page refreshed
Page refreshed
Page refreshed
 0 secondsTraceback (most recent call last):
  File "C:/Users/Me/PycharmProjects/bestbuybot/bestbuy.py", line 168, in <module>
    findingCards(driver)
  File "C:/Users/Me/PycharmProjects/bestbuybot/bestbuy.py", line 163, in findingCards
    timeSleep(5, driver)
  File "C:/Users/Me/PycharmProjects/bestbuybot/bestbuy.py", line 32, in timeSleep
    driver.refresh()
  File "C:\Users\Me\PycharmProjects\bestbuybot\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 831, in refresh
    self.execute(Command.REFRESH)
  File "C:\Users\Me\PycharmProjects\bestbuybot\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Me\PycharmProjects\bestbuybot\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=netTimeout&u=https%3A//www.bestbuy.com/site/searchpage.jsp%3F_dyncharset%3DUTF-8%26id%3Dpcat17071%26iht%3Dy%26keys%3Dkeys%26ks%3D960%26list%3Dn%26qp%3Dcategory_facet%253DGPUs%2520%252F%2520Video%2520Graphics%2520Cards%7Eabcat0507002%26sc%3DGlobal%26st%3Drtx%25203080%26type%3Dpage%26usc%3DAll%2520Categories&c=UTF-8&d=%D0%92%D1%80%D0%B5%D0%BC%D1%8F%20%D0%BE%D0%B6%D0%B8%D0%B4%D0%B0%D0%BD%D0%B8%D1%8F%20%D0%BE%D1%82%D0%B2%D0%B5%D1%82%D0%B0%20%D0%BE%D1%82%20%D1%81%D0%B5%D1%80%D0%B2%D0%B5%D1%80%D0%B0%20www.bestbuy.com%20%D0%B8%D1%81%D1%82%D0%B5%D0%BA%D0%BB%D0%BE.

Process finished with exit code 1

**Comment by IIe4eHbkas** [comment]
Page refreshed
Page refreshed
 0 secondsTraceback (most recent call last):
  File "C:/Users/Me/PycharmProjects/bestbuybot/bestbuy.py", line 168, in <module>
    findingCards(driver)
  File "C:/Users/Me/PycharmProjects/bestbuybot/bestbuy.py", line 163, in findingCards
    timeSleep(5, driver)
  File "C:/Users/Me/PycharmProjects/bestbuybot/bestbuy.py", line 32, in timeSleep
    driver.refresh()
  File "C:\Users\Me\PycharmProjects\bestbuybot\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 831, in refresh
    self.execute(Command.REFRESH)
  File "C:\Users\Me\PycharmProjects\bestbuybot\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Me\PycharmProjects\bestbuybot\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 


Process finished with exit code 1

**Comment by ckennedy421** [comment]
I am having this same error. New deployment, will refresh the page a few times then throw this error with exit code 1.

**Comment by VincentViscusi** [comment]
same thing for me basically i posted a issue about it also :( I just want to ready for the 3080s coming out next week soon because i could’ve had last week but it did the same thing
